# SPDX-License-Identifier: LGPL-3.0-only
# Copyright 2026 Canonical Ltd.

name: SAST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  gosec:
    name: Gosec security scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run gosec
        uses: securego/gosec@deb54465fea23d19a77f037e11e6589021f8501d # v2.29.0
        with:
          args: ./...

  govulncheck:
    name: Go vulnerability check
    runs-on: ubuntu-latest
    steps:
      - name: Run govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
